services:
  - type: web
    name: ebay-book-scanner
    env: node
    plan: starter
    buildCommand: ""
    startCommand: node server.js
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: EBAY_MARKETPLACE_ID
        value: EBAY_US
      - key: EBAY_ENV
        value: production
      - key: EBAY_CLIENT_ID
        sync: false
      - key: EBAY_CLIENT_SECRET
        sync: false
